- package.json
- src/index.js
- test.js
- tests/build.js
- tests/fixture_combine_styles.js
I want to get initial thoughts. I used concat-with-sourcemaps to make it possible to generate sourcemap for concatenated styles.
Also it looks with this option, it does not looks usefull to have separate style tags. 
What do you think about naming, code etc?
> Add option to combine all style tags to one

- src/index.js
> fix options.extract : string

- src/less-loader.js
Change-Id: I0605865ba017e55530768ec91bb2f17b2c132e9a
> fix: fix less file not found

- src/index.js
Just need to check if dirname is there already before pre-pending to source path
> fixes #135 check map.source before pre-pending dirname

- package.json
- yarn.lock
> update postcss-modules to support camelCase option

- appveyor.yml
- circle.yml
> chore: use node.js lts on CI

- .github/workflows/ci.yml
> chore: use Github Actions

- .github/workflows/release.yml
- package.json
> chore: add Semantic Release on Github Actions

- src/index.js
- src/utils/humanlize-path.js
> fix: windows path

- .github/workflows/release.yml
https://github.com/egoist/rollup-plugin-postcss/runs/461892720#step:3:130
> fix: Github Actions release.yml incorrect

- .github/workflows/release.yml
> ci: fix releasing package

- package.json
- src/postcss-loader.js
- test/__snapshots__/index.test.js.snap
- test/fixtures/named-exports/style.css
- yarn.lock
> fix: class named 'default' throws an error when options.namedExports

- README.md
- src/index.js
- test/__snapshots__/index.test.js.snap
- test/index.test.js
> feat: allow to pass options to built-in loaders

- README.md
- src/index.js
- src/postcss-loader.js
- test/__snapshots__/index.test.js.snap
- test/index.test.js
related #247, #245, #199, #185, #177, #120
> inject option function support

- src/index.js
Fixes #250
This reverts commit ecadc6cd
> Revert "Use this.emitFile for emitting files (#244)"

- package.json
- types/index.d.ts
close #172
need update `PostCssPluginOptions`
> feat: add typescript declaration file

- README.md
Quick documentation amend. Had to do some extra digging today to discover this, so thought I'd add here.
> Document extract to custom file name

- src/postcss-loader.js
- https://github.com/rollup/rollup/blob/c0c206e2a8a892fdb0e4f9b25b0a817b733a072f/cli/run/batchWarnings.ts#L178
- https://github.com/rollup/rollup/blob/c0c206e2a8a892fdb0e4f9b25b0a817b733a072f/cli/run/batchWarnings.ts#L183
- https://github.com/postcss/postcss/blob/d7a1923008cf5c40c9b327ef37bc852f90252d2a/lib/postcss.d.ts#L420
> fix: add missing warning.message

- src/index.js
- test/__snapshots__/index.test.js.snap
- test/fixtures/multi-entry/entry1-extra.css
- test/fixtures/multi-entry/entry1.css
- test/fixtures/multi-entry/entry1.js
- test/fixtures/multi-entry/entry2.js
- test/index.test.js
Reverts egoist/rollup-plugin-postcss#264
> Revert "feat: support for multiple entry files"

- src/postcss-loader.js
- test/__snapshots__/index.test.js.snap
Closes: https://github.com/egoist/rollup-plugin-postcss/issues/282
> fix: replace const keyword with var keyword in output
