package.json, src/index.js, test.js, tests/build.js, tests/fixture_modules.css, tests/fixture_modules.js
Optional function to configure the return value of the injected module.
I just wanted to get some feedback on this. It depends on egoist/style-inject#1 and fixes #2
You can configure `rollup` like so
```js
const postcss = require('rollup-plugin-postcss');
const postcssModules = require('postcss-modules');
const cssExportMap = {};
rollup({
plugins: [
postcss({
plugins: [
postcssModules({
getJSON (id, exportTokens) {
cssExportMap[id] = exportTokens;
}
})
],
getExport (id) {
return cssExportMap[id];
}
})
]
})
```
And it allows you to do
```js
import style from './style.css';
console.log(style.className); // .className_echwj_1
```
I didn't want this plugin to be aware of `postcss-modules` but simply provide a generic way of injecting the exported module.
This approach has the downside of …
=> Allow to define what's exported

.gitignore, README.md, package.json, src/index.js, test.js, tests/build.js
This is a response to [#4.](https://github.com/egoist/rollup-plugin-postcss/issues/4)
This PR adds an additional option, `extract`, which is expected to be a string or a boolean. When a path is provided as the value to `extract`, at the end of the build, a css file will be output to that path. If `extract` is true(bool) the css file will be output at the same path as the chosen rollup's bundle.write `dest` option.
When the option `sourceMap` is present and true-y an inline source map of the css will also be created.
This solution doesn't break other options and behaviors of the actual plugin.
=> Add extract option to write combined css and source map

src/index.js
Hi, I've stumbled upon an interesting bug while trying to configure my dev environment with rollup watch mode (added with `rollup-watch` module). Example:
While using `extract` option and `--watch` flag importing following CSS file:
```
body {
color: red;
}
```
I am getting correct bundled CSS file. But trying to modify source CSS file, for example:
```
body {
color: green;
}
```
Results in following bundled CSS:
```
body {
color: red;
}
body {
color: green;
}
```
While using watch mode `transform` function is only invoked for modified file. Since `concat-with-sourcemaps` is initialized before and support only `add` method all modified files are appended to existing content. I would qualify my fix as a hack since it is basically storing all the CSS files and concatenating them before …
=> Remove appending styles in watch mode

README.md, src/index.js, test/fixtures/fixture_modules.css, test/fixtures/fixture_modules.js, test/test.js
When using the plugin `postcss-modules` allow for exporting each individual generated className apart from the default style object.
So now we can use :
`import {specificClassName} from "style.css"`
This PR is a response to #14
=> #14 option to not default export

README.md, src/index.js, test/fixtures/fixture_modules.css, test/fixtures/fixture_modules.js, test/test.js
This PR is trying to fix an issue where exporting a selector which including dashes like `.foo-bar` when using css modules. Since now we are generating `export const foo-bar = "....."` and the dashes are illegal for javascript variables, the whole build phrase would fail.
I'm just implementing `camelCase: 'dashes'` option in [webpack-style-loader](https://github.com/webpack-contrib/css-loader#camelcase). It's fairly enough for my use cases.
=> camlCase dashes for css modules exports

package.json, src/index.js, test/fixtures/fixture_modules.css, yarn.lock
This PR is trying to fix an issue when using js reserved keywords like `switch` as css class names.
Though I can't figure out how to write the test for this case, the tests would throw the error without this patch.
=> fix js reserved keyword as classname

README.md, src/index.js, test/build.js, test/fixtures/fixture_modules.css, test/fixtures/fixture_modules.js, test/fixtures/fixture_modules_export_named.js, test/test.js, yarn.lock
- fixed wrong sourcemap reference with manual destination (#32, #33)
- added getExportNamed param to allow/ named exports when used with css
modules (#27, #30)
- when using name exports, all the classNames that contains dashes, or
they are js protected names, will be transformed to usable js names.  (#27, #28)
- name transformations are logged out for usage information.
- added new unit tests and updated existing tests to cover more scenarios
=> Transform named exported classNames to accepted js var names and other fixes

CHANGELOG.md, README.md, package.json, src/helpers.js, src/index.js, src/watcher.js, test/build.js, test/fixtures/fixture_modules.css, test/fixtures/fixture_modules.js, test/fixtures/fixture_modules_export_named.js, test/test.js, yarn.lock
Postcss and rollup are [not watching the changes made to the imported files](https://github.com/lmihaidaniel/rollup-plugin-postcss-export/issues/3).
This PR helps solve this rather frustrating issue by providing a watcher, to which the users can dynamically feed the names of files, which they wish to watch. The filenames can be extracted using the `postcss-import`'s or the `postcss-less-engine` plugin's `onImport` handler.
Example rollup config:
```javascript
import postcss from 'rollup-plugin-postcss'
import less from 'postcss-less-engine'
const isWatching = process.argv.includes('-w') || process.argv.includes('--watch')
let watcher
export default [{
entry: 'src/index.less',
dest: 'dist/dummy',
plugins: [
postcss({
extensions: ['.less'],
extract: './dist/test.css',
getInstance: …
```
=> Added watch functionality for imported files

package.json, src/index.js, test/build.js, test/test.js, yarn.lock
- Removed unnecessary dead code from the unit testing
- Updated to the latest rollup config changes, providing also backwards compatibility :
* `sourceMap` can be `sourcemap` or `sourceMap`
More info on rollup config changes, here: 
https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32
=> Update to latest rollup config changes.

src/index.js
The code exported by this plugin is directly included in the code outputted by rollup. If this plugin is included in a project that targets ES5, using this plugin requires that project integrates babel into rollup in order to transform the `const` into `var`. In reality, since many projects do use Babel, this problem likely affects TypeScript projects, which don't necessarily use babel.
Would you be willing to consider changing the `const` to `var` so this plugin no longer requires babel?
Currently, I can easily work around this by including babel so it's not a big blocker, but I thought I'd at least ask. :)
To be clear, in my current project, I compile my TypeScript to JavaScript (instructing TypeScript to output ES6 module syntax), and then run Rollup against that JavaScript.
=> Emit `export var` instead of `export const`

src/index.js
When using the extract option along with CSS-modules and rollup-watch
any modification of a CSS-file will only emit the output of the modified
file, ignoring all other modules which have already been built and
overwriting the file contents, resulting in broken CSS.
This modification keys extracted data with its ID in a Map, allowing
incremental rebuilds while preserving order.
=> Support for incremental rebuilds

src/postcss-loader.js
If you are using the [`postcss-import`](https://github.com/postcss/postcss-import) plugin, it requires that it be the first plugin passed to PostCSS ([See first note](https://github.com/postcss/postcss-import/blob/master/README.md) in the `postcss-import` README). Currently `rollup-plugin-postcss` puts the `postcss-modules` plugin first in the list of PostCSS plugins causing an issue if you use CSS Modules `composes` from an external file together with `@import` syntax from the `postcss-import` plugin. The issue is the data from `@import` gets wiped out by the inlining done by `composes` from `postcss-modules`. Example..
**Input**
```
// shared/border-radius.css
.all {
border-radius: 3px;
}
```
```
// shared/colors.css
:root {
--white: #fff;
}
```
```
// main.css
@import …
```
=> Fix issues with using postcss-import plugin and postcss-modules plugin

README.md
Hi,
I've found this particular part quite confusing, so tried to detail it a bit more.
Also to note, one can't override the other context keys from this plugin.
=> Clarify the  and  options documentation

package.json, src/less-loader.js, src/postcss-loader.js, src/sass-loader.js, src/stylus-loader.js, src/utils/local-require.js, yarn.lock
This package uses a more-accurate module resolution algorithm. It's basically just a wrapper around the `import-from` package @egoist suggested in #84, by the same author.
=> Replace localRequire with the `import-cwd` package

src/sass-loader.js, test/fixtures/sass-import/_partial.scss, test/fixtures/sass-import/foo.scss, test/fixtures/sass-import/node_modules/foo/bar/_partial.scss, test/fixtures/sass-import/style.scss
This fixes #86 by handling importing Sass partials from node_modules, so that something like this will work properly: `@import ~foo/bar/partial` where "partial" has the filename "_partial.scss".
=> fix: handle importing Sass partials in node_modules

package.json, src/sass-loader.js, yarn.lock
This PR introduces a worker queue which limits the number of concurrent threads similar to how webpack [sass-loader](https://github.com/webpack-contrib/sass-loader/blob/2529c0716b1bca321c22d16636b1385682b1c730/lib/loader.js#L14) does. The changes are a workaround for the issues in node-sass discussed in https://github.com/egoist/rollup-plugin-postcss/issues/104.
=> Limit threads when transpiling with node-sass

package.json
This is a fairly big upgrade and should be done asap imo. Most notably, `cssnano@4` runs on the latest Browserslist, which supports the `dead` query. Babel@7 also runs on this version of Browserslist, so until this dependency gets updated, a single `"browserslist"` config will be incompatible between tools.
---
_Closes #121_
=> Chore: Upgrade cssnano

src/postcss-loader.js, test/__snapshots__/index.test.js.snap, test/index.test.js
Hey~!
As of now, there's no way to access the JSON file of classnames to their outputs. It can only happen thru the [`getJSON` method of `postcss-modules`](https://github.com/css-modules/postcss-modules#saving-exported-classes), but it's overridden here.
This PR allows a user to define a custom `getJSON` method, passing it all arguments for them to do as they please. It does not affect the core behavior of the plugin.
---
_Also closes #101_
=> Allow custom `modules.getJSON` function

src/index.js
Allow boolean plugins similar to how Rollup plugins work. In the Rollup plugins array you may write the following to only run a plugin for production usage:
```js
plugins: [
(process.env.NODE_ENV === 'production' && terser())
]
```
This pull request allow the same approach for PostCSS plugins:
```js
plugins: [
(process.env.NODE_ENV === 'production' && cssnano())
]
```
[Example of how Rollup has implemented this feature.](https://github.com/rollup/rollup/blob/f58d1e60a3da4b8470e5d56aa0caef2ecadec2b8/src/rollup/index.ts#L107)
=> Allow boolean plugins support

.gitignore, src/less-loader.js, src/sass-loader.js, src/stylus-loader.js, src/utils/load-module.js
Hello!
Right now `rollup-plugin-postcss` loads dependencies like `node-sass` using `import-cwd` utility, which searches for modules strictly in the current working directory of the executing script. In the general use case this could be working correctly, however, if you have a more non-trivial setup or you are not running Rollup in the expected directory this will lead to modules not being found.
Also, this approach doesn't respect [Node Module Resolution Algorithm](https://nodejs.org/api/modules.html#modules_all_together) at full, e.g. it completely ignores the `NODE_PATH` environment variable.
This PR fixes these issues by implementing two-step loading mechanism, first, it tries to load the requested module normally using conventional resolution algorithm and then it falls back to …
=> feat: implemented more robust module loading

src/postcss-loader.js, test/__snapshots__/index.test.js.snap
Added support for consuming stringfied bundle of the css code to be injected from JS.
Basically, when setting up the option 'extract' with this change we will have the capacity to inject anywhere the bundled css from straight from the JS without having to inject it in the .
image. 
The stringfied bundled css will be exported as a const named `stylesheet`
This poses a great advantage in terms of confectioning your own web components with CSS modules and injecting the styles in a custom <style> tag at the coder's discretion.
Here is a screenshot of the overall result.
Please feel free to reach me to discuss it any further.
=> Added support for consuming stringfied bundle of the css code to be injected from JS.

src/sass-loader.js, test/__snapshots__/index.test.js.snap, test/fixtures/sass-data-prepend/_prepend.scss, test/fixtures/sass-data-prepend/index.js, test/fixtures/sass-data-prepend/style.scss, test/index.test.js
> Originally by @bastienrobert on #179 (currently has conflicts). I'm hoping this new PR will be friendlier to merge.
Adds `data` prepend feature common on sass-loader implementations.
**Example:** https://github.com/differui/rollup-plugin-sass#options-1
cc @cortopy @egoist
=> [sass-loader] Prepend options.data to code payload

CHANGELOG-OLD.md
Caused links to point to GitHub's 404 page
=> Remove colon from Github URLs

README.md, src/index.js, src/postcss-loader.js
Added support for PostCSS to option for some plugins that are relying on it
Fixes #145
Almost all PostCSS asset rebase plugins are relying on `to` options to properly rebase path and with hardcoded value for `to` they just don't work. This PR addresses this issue and adds `to` option that could be explicitly set if it is needed.
=> Added support for PostCSS "to" option for some plugins that are relying on it

src/index.js
This pull request fixes the following warning that occurs in Rollup 2.x:
>(!) A plugin is directly adding properties to the bundle object in the "generateBundle" hook. This is deprecated and will be removed in a future Rollup version, please use "this.emitFile" instead.
=> Use this.emitFile for emitting files

src/loaders.js
Setting the test on the loader itself means that a second instance of the plugin would override the previous test.
My config looks like this fwiw:
```js
export default () => {
return {
input: {},
output: {},
plugins: [
// ...
postcss({
extensions: ['.css'],
include: ['**/*.css'],
use: []
}),
postcss({
extensions: ['.less'],
include: ['**/*.less'],
use: ['less']
}),
postcss({
extensions: ['.lcss'],
include: ['**/*.lcss'],
use: [],
modules: true,
namedExports: true
}),
// ...
]
};
};
```
BTW I have to add the `include`s, otherwise I'm hitting a bug where the plugin tries to re-parse a stylesheet, but the code has already been transformed to JS. 🤔
=> Fix using multiple postcss() plugin instances

src/utils/load-module.js
Release 3.6.* introduced the following line: https://github.com/egoist/rollup-plugin-postcss/blob/75306fb54307573dbad9438da92664ced74c63e3/src/utils/load-module.js#L8-L9
Judging from the comment, this wasn't supposed to be published. Now even if one of the modules exists, the error will be thrown if it's not first in the list (i.e. when using `sass` instead of `node-sass`).
=> Remove error logging in `loadModule`

README.md
BREAKING CHANGE: v3 not support rollup v1.
extract relative path based on bundle root.
=> docs: add v3 usage

src/index.js, test/__snapshots__/index.test.js.snap, test/fixtures/multi-entry/entry1-extra.css, test/fixtures/multi-entry/entry1.css, test/fixtures/multi-entry/entry1.js, test/fixtures/multi-entry/entry2.js, test/index.test.js
Continuing on the work of https://github.com/egoist/rollup-plugin-postcss/pull/230
This is a basic example for support for bundling multiple css files based on the number of entries. Rationale being that if you are using js modules and might have multiple entries you might not need to load all of the css at once. This would be handled in some user chosen way.
There is one question though, how to handle the `extract: "some/custom/path"` in such cases:
1. Put files relative to the entry points. This most likely will brake some people code.
2. In case of `extract` being a string fall back to single css file output.
Would need more input from the team on this.
=> feat: support for multiple entry files

src/index.js, src/postcss-loader.js, test/index.test.js
This includes a fix for #281
Comparison of the options logic (IS / SHOULD columns):
| Case |                   | opt autoModules | opt modules | -- will be module? |  IS | SHOULD |
|------|-------------------|-----------------|-------------|--------------------|----:|-------:|
| 1    | styles.css        | false           | false       |                    |     |        |
| 2    | ...               | false           | true        |                    | yes |    yes |
| 3    | ...               | true            | false       |                    |     |        |
| 4    | ...               | true            | true        |                    | yes |    yes |
| 5    | ...               | false           | {}          |                    | yes |    yes |
| 6    | ...               | true …
=> fix: allow module config while using autoModules (#281)

package.json
Hi there :wave:
While using this module in a project I noticed that the types file specified
doesn't get published to npm when this package is published. I've added it in in this PR.
Thanks for maintaining this module!
=> fix: Add types file to package.json files

src/index.js, test/__snapshots__/index.test.js.snap
For the example in:
`test/fixtures/dist/extract--custom-path/this/is/extracted.css`
the sourceMappingURL was:
`/*# sourceMappingURL=this/is/extracted.css.map */`
Meaning the browser would try and load the sourcemap from:
`this/is/this/is/extracted.css.map`
This only happens when someone has set `extract` to something like `this/is/extracted.css`.
I've changed this to run the map name through path.basename first, as the map is always dropped in the same folder as the css file.
=> fix: make sourceMaps relative to the CSS output file

package.json
This commit should trigger semantic versioning and also put peer dep to 8.x instead of 8.1.14
=> BREAKING CHANGE: move postcss peerdep 8.x

package.json, src/index.js, test/__snapshots__/index.test.js.snap, yarn.lock
Fix https://github.com/egoist/rollup-plugin-postcss/issues/350
Update cssnano to the latest releasse: https://github.com/cssnano/cssnano/releases/tag/cssnano%405.0.0
Also possibly fix https://github.com/egoist/rollup-plugin-postcss/issues/340 (need to check this)
=> refactor: update to cssnano 5.

src/sass-loader.js
Prioritizes dart-sass (`sass`) over `node-sass` when both are available
[`node-sass` is deprecated](https://www.npmjs.com/package/node-sass), as is its underlying LibSass.
Modern Sass features such as `@use` [cannot and will not be supported by `node-sass`](https://github.com/sass/node-sass/issues/2886)
In projects where both dependencies are available, this change will prevent the deprecated `node-sass` from running against modern SCSS code that may require dart-sass to compile.
While a configurable option for the preferred loader would be a more robust solution, it would require much more extensive changes to the plugin. This is a simple solution that will resolve the core problems experienced in issues #321 and #304, and involves minimal changes to the plugin code, leveraging the …
=> fix: prioritize dart-sass over deprecated node-sass
